app/urls.py
from .import views
from django.conf.urls import url

from shopping import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

app_name="app"

urlpatterns=[
    url(r'home',views.home,name="home"),
    url(r'log',views.log,name="log"),
    url(r'modify',views.modify,name="modify"),
    url(r'(?P<product_id>[0-9]+)/yoo$',views.yoo,name="yoo"),
    url(r'(?P<product_id>[0-9]+)/top$',views.top,name="top"),
    url(r'(?P<collection_id>[0-9]+)/prod$',views.prod,name="prod"),
    url(r'(?P<product_id>[0-9]+)/nope$',views.nope,name="nope"),
    url(r'(?P<product_id>[0-9]+)/dele$',views.dele,name="dele"),
    url(r'thanks',views.thanks,name="thanks"),
    url(r'username/',views.usernamevarify,name="usernamevarify"),
    url(r'signup',views.signup,name="signup"),
    url(r'ishank',views.ishank,name="user_logout"),
    url(r'cust/',views.cust,name="cust"),
    url(r'deepak/',views.deepak,name="deepak"),
    url(r'sumi/$',views.sumi,name="sumi"),
    url(r'search$',views.search,name="search"),
    url(r'wifi$',views.wifi,name="wifi"),
    url(r'orders$',views.orders,name='orders'),
    url(r'(?P<order_id>[0-9]+)/soonn$',views.soonn,name="soonn"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('app.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save,post_save,m2m_changed
class Collection(models.Model):
    p_name=models.CharField(max_length=100)
    def __str__(self):
        return self.p_name

class Product(models.Model):
    collect=models.ForeignKey(Collection,on_delete=models.CASCADE)
    name=models.CharField(max_length=40)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    brand=models.CharField(max_length=50)
    features=models.CharField(max_length=100)
    img=models.FileField(upload_to='media')
    stock=models.IntegerField()

    def __str__(self):
        return self.name+self.brand


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    name=models.CharField(max_length=50)
    mob=models.IntegerField()
    pin=models.IntegerField()
    address = models.CharField(max_length=100)
    city=models.CharField(max_length=50)
    country=models.CharField(max_length=30)
    state=models.CharField(max_length=40)
    def __str__(self):
        return self.name
class Cart(models.Model):
    cust=models.OneToOneField(User,on_delete=models.CASCADE,default=None)
    products=models.ManyToManyField(Product)
    total=models.DecimalField(max_digits=100,decimal_places=2,default=0.00)
    def _str__(self):
        return str(self.pk)

def m2mchanged_product(sender,action,instance,*args,**kwargs):
    products=instance.products.all()
    total=0
    for product in products:
        total+=product.price
    instance.total=total
    instance.save()
m2m_changed.connect(m2mchanged_product,sender=Cart.products.through)

class Order(models.Model):
    cust=models.ForeignKey(Customer,on_delete=models.CASCADE)
    products=models.ManyToManyField(Product,blank=True,null=True)
    cash=models.DecimalField(max_digits=100,decimal_places=2,default=0.00)
    def __str__(self):
        return str(self.pk)

def cash_changed(sender,action,instance,*args,**kwrgs):
    products=instance.products.all()
    cash=0
    for p in products:
        cash+=p.price
    instance.cash=cash
    instance.save()

m2m_changed.connect(cash_changed,sender=Order.products.through)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Shopkart.in</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/mdb.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/mdb.lite.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/mdb.lite.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styl.css' %}">
    {% block head %}
    {% endblock %}

</head>
<body>

    {% block body %}
    {% endblock %}
    {% block javascript %}
    {% endblock %}
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/mdb.min.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/ajax.jquery.min.js' %}"></script>
    <script src="{% static 'jquery.magnify.js' %}"></script>
    <script src="{% static 'jquery.magnify-mobile.js' %}"></script>

</body>
</html>

templates/carousel.html
<div class="form">
        <div class="row">

            <div class="col-md-6 text-left">
                <div class="pop">
                <center><h2>LogIn form</h2></center>
                <form class="form-group p-5 text-left" method="post" action="">
                    {% csrf_token %}
                    <label>UserName</label>
                    <input type="text" class="form-control" name="t1">
                    <label>Password</label>
                    <input type="password" name="t2" class="form-control">
                    <br>
                    <input type="submit" class="btn btn-outline-dark">
                    <input type="reset" class="btn btn-outline-dark">
                 </form>
                </div>
            </div>
            <div class="col-md-6">
                <div style=" display:none">
                <center><h3 class="m-2">SignUp Form</h3></center>
                <form class="form-group p-5" method="post" action="">
                    {% csrf_token %}
                    <label>Name</label>
                    <input type="text" name="t1" class="form-control">
                    <label>Email</label>
                    <input type="email" name="t3" class="form-control">
                    <label>Contact Number</label>
                    <input type="number" name="t4" class="form-control">
                    <label>PIN</label>
                    <input type="number" name="t5" class="form-control">
                    <label>Address</label>
                    <textarea rows="4" cols="26" name="t6" class="form-control"></textarea>
                    <label>City</label>
                    <input type="text" name="t7" class="form-control">
                    <label>State</label>
                    <input type="text" name="t8" class="form-control">
                    <label>Country</label>
                    <input type="text" name="t9" class="form-control">
                    <label>UserName</label>
                    <input type="text" name="t10" class="form-control">
                    <label>Password</label>
                    <input type="password" name="t11" class="form-control">
                    <br>
                    <input type="submit" class="btn btn-outline-dark" value="Register">
                    <input type="reset" class="btn btn-dark" value="Reset">

            </form>
                </div>

            </div>
        </div>

    </div>

templates/coo.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
        $(".lol").hide();
        $("button").click(function(){
           $(".lol").toggle();
        });
    });
    </script>
{% endblock %}

{% block body %}
{% include 'navbar.html' %}

        {% if user.cart.products.all %}
<center><h2 class="text-primary">Your welcome <u>{{ user.customer.name }}</u> in the world of fashion.</h2></center>
<div class="container">
    <div class="row my-4">
        {% for i in q.products.all %}
            <div class="card">
            <div class="card-body">
                <img src="{{ i.img.url }}" width="250px" height="250px">

            </div>
            <div class="card-footer bg-white">
                <center>
                    <h3>{{ i.name }}</h3>
                    <h5>Rs {{ i.price }}</h5>
                    <a href="{% url 'app:dele' i.id %}" class="btn btn-primary">Remove From Cart</a>

                </center>
            </div>
            </div>

        {% endfor %}
        <br>
        <hr>
    <div class="container m-4">
        <div class="row m-3">
            <div class="col-md-6">
                <center>
                    <h2>Address</h2>
                    <h5>Place your order at</h5>
                    <h5>{{ user.customer.address }}</h5>
                    <h5>{{ user.customer.mob }}</h5>
                    <h5>{{ user.customer.city }}</h5>
                    <h5>{{ user.customer.state }}</h5>

                    <button type="button" class="btn btn-primary">Modify your address</button>
                </center>
            </div>
            <div class="col-md-4 my-3">
                <center>
                    <div class="card p-3">
                        <h2 class="text-danger">Pay Rs {{ q.total }}</h2>
                        <hr>
                        <a href="/deepak" class="btn btn-primary">Buy Now</a>
                        <h4>Pay when order is delivered to you</h4>
                    </div>
                </center>
            </div>
        </div>
    </div>
    </div>
    </div>


    <div class="container lol">
        <center><h2 class="text-primary">Address Modification Form</h2></center>
    <form class="form-group"  action="/wifi" method="post">
            {% csrf_token %}
    <div class="row my-5" style="margin-left:100px;">

        <div class="col-md-6">
            <label>Name</label>
            <input type="text" required name="t1" value="{{ user.customer.name }}" class="form-control">

            <label>Contact Number</label>
            <input type="number" name="t4" required class="form-control">
            <label>PIN</label>
            <input type="number" name="t5" required class="form-control">
            <label>Address</label>
            <textarea rows="4" cols="26" name="t6" required class="form-control"></textarea>

        </div>
        <div class="col-md-6">
            <label>City</label>
            <input type="text" name="t7" required class="form-control">
            <label>State</label>
            <input type="text" name="t8" required class="form-control">
            <label>Country</label>
            <input type="text" name="t9" required class="form-control" value="India">
            <br>
            <input type="submit" class="btn btn-outline-dark" value="Register">
            <input type="reset" class="btn btn-dark" value="Reset">

        </div>
    </div>
        </form>
    </div>
    </div>
    {% endif %}

{% endblock %}

templates/footer.html
<div class="foot p-5">
    <center>
    <h1 class="p-4"> All Copyright &copy; are reserved</h1>
    <h3>Developed and maintained by Ishank Chopra</h3>
        </center>
</div>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="top-bar py-1 bg-light">
    <div class="container">
    <div class="row ">
        <div class="col-md-7 my-1 p-1">
            <a href="#"><i class="fa fa-2x fa-facebook"></i></a>
            <a href="#"><i class="fa fa-2x fa-twitter px-2"></i></a>
            <a href="#"><i class="fa fa-2x fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-2x fa-youtube px-2"></i></a>
        </div>
        <div class="col-md-5 my-1 p-2">
            <i class="fa fa-2x fa-phone pr-2"></i>(+91-7985676179)
            <i class="fa fa-2x fa-envelope px-2"></i>ishu.ishank1411@gmail.com

        </div>
    </div>
    </div>
</div>
{% include 'navbar.html' %}

        <div class="site-blocks-cover overlay"  data-aos="fade" data-stellar-background-ratio="0.5">
            <div class="container text-white">
                <div class="hod">
                    <h1 class="opo">Shop With Us</h1>
                    <br>
                    <p class="oyo">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aperiam, doloremque eius ex neque vero?</p>

                <br>
                <a href="/log" class="btn btn-outline-white text-white">LogIn Yourself</a>
                <a href="/log" class="btn btn-white text-dark">Create your account</a>

                </div>
            </div>
    </div>
    <div class="container">
        <div class="row my-3">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <center>
                <h5 style="color:darkgray">Popular Products</h5>
                <h1 class="my-3 ok">Our Products</h1>
                <p style="color:darkgray">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus doloribus ipsum laborum minus natus nulla obcaecati officiis perferendis unde? Expedita labore nesciunt quasi qui ut velit. Amet aperiam nisi voluptate.</p>
            </center>
        </div>
        </div>
    </div>
    <div class="container">


    <div class="row bg-white">
        {% for i in m|slice:":4" %}
            {% for j in i.product_set.all|slice:":2" %}
                <center>
                    <div class="item">
                        <a href="{% url 'app:prod' i.id %}"><img src="{{ j.img.url }}" width="250px" height="250px" class="img m-3"></a><br>
                        <h3 class="m-3 ">{{ j.name }}</h3>
                        <p class="m-2">Rs{{ j.price }} Only/</p>
                    </div>
                </center>
            {% endfor %}
            <br>
            <hr>
            {% endfor %}
    </div>
    </div>
    <hr>
    <br>

    <div id="about">
    <div class="uy">
        <div class="container lko bg-light">
        <center>
            <h1>About Shopkart.in</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus architecto, aut autem blanditiis cupiditate eaque esse eum expedita illum impedit ipsam iure magnam minus, nam non perferendis quo tempore voluptatibus?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam cupiditate debitis delectus exercitationem id, iste iure maxime, modi mollitia, neque perferendis possimus quas quidem rem repellat rerum sed sit totam velit! Minus, necessitatibus, similique?</p>
        </center>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-8">
                <img src="{% static 'image/pp.jpg' %}" class="img-thumbnail" width="650px" height="auto">
            </div>
            <div class="col-md-4 mt-5">
                <center>
                    <h2>ShopKart.in</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur dolores est et expedita inventore rem temporibus velit voluptates? Commodi culpa ducimus ex magni obcaecati odit optio suscipit. At, id, illo.</p>
                    <h3>Ishank Chopra</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda at commodi cumque delectus dignissimos, ea expedita explicabo facilis impedit incidunt nemo officia omnis provident quod sint sit sunt tempore temporibus!</p>
                    <br><br>
                    <div class="box">
                        <h3>Trusted Merchant</h3>
                        <p>For 50 years</p>
                    </div>
                </center>
            </div>

        </div>
    </div>
    </div>
    <div class="container-fluid bg-light p-5">
    <center>
        <h2>GET in Touch/Sign Up Form  </h2>
        <p>After creating your account we update you with or exciting offers. So hurry up to get latest deals only on shopkart.in</p>

    </center>
    <div class="form">
        <center><h3 class="m-4">Contact Form</h3></center>
        <form class="form-group p-5" method="post" action="">
            <div class="row ">
                <div class="col-md-5">
                    <label>First Name</label>
                    <input type="text" name="t1" class="form-control">
                </div>
                <div class="col-md-5">
                    <label>Second Name</label>
                    <input type="text" name="t2" class="form-control">
                </div>

            </div>
            <label>Email</label>
            <input type="email" name="t3" class="form-control">
            <label>Subject</label>
            <input type="text" name="t4" class="form-control">
            <label>Message</label><br>
            <textarea rows="5" cols="35"></textarea>
        </form>

    </div>
    </div>
{% include 'footer.html' %}

{% endblock %}

templates/item.html
{% extends 'base.html' %}
{% load static %}
{% include 'navbar.html' %}

{% block body %}
{% include 'navbar.html' %}
    {% for i in a %}
    <div class="row m-2">
        <div class="col-md-2"></div>
        <div class="col-md-4 ">
            <a href="{% url 'app:yoo' i.id %}"><img src="{{ i.img.url }}" class="zom" width="300px" height="300px"></a>
        </div>
        <div class="col-md-6">
            <h3>{{ i.name }}</h3>
            <h4>{{ i.price }}</h4>
            <h4>{{ i.features }}</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium corporis error id illum iusto repellat. Consequatur cum, debitis disti</p>

            <h3>Only <u>{{ i.stock }}</u> left. Hurry Up</h3>
            <div class="row">
                <div class="col-md-6">
                    <center><a href="{% url 'app:yoo' i.id %}" class="btn btn-outline-dark text-black">Buy Now</a></center>
                </div>
            </div>
        </div>
    </div>
        <hr>
    {% endfor %}
{% endblock %}

{% include 'footer.html' %}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-md p-3 bg-white sticky-top ">
    <div class="container text-dark">
        <a href="#" class="navbar-brand op">Shopkart.in</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#dropdownNavbar">
            <span class="fa fa-3x fa-envelope"></span>
        </button>
        <div class="collapse navbar-collapse text-right" id="dropdownNavbar">
            <ul class="navbar-nav">
                <li class="nav-item"><a href="/home" class="nav-link  oyo">Home</a></li>
                <li class="nav-item"><a href="#about" class="nav-link  oyo">About Us</a></li>
                {% if user.customer %}
                <li class="nav-item"><a href="/cust" class="nav-link oyo"> Welcome {{ user.customer }}</a></li>
                <li class="nav-item"><a href="/ishank" class="nav-link oyo">LogOut</a></li>
                {% else %}
                <li class="nav-item"><a href="/log" class="nav-link  oyo">Log in </a></li>
                {% endif %}

            </ul>
        </div>
        <form class="form-inline" action="/search" method="post">
            {% csrf_token %}
            <input type="text" class="form-control" name="t1" placeholder="search...">
            <button type="submit" class="btn btn-outline-dark">Submit</button>
        </form>
    </div>
</nav>

templates/order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Shopkart Orders</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/mdb.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/mdb.lite.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/mdb.lite.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styl.css' %}">

</head>
<body>

    {% for i in a %}
        <div class="row my-4">
        <div class="col-md-2">

        </div>
        <div class="col-md-6">
            <center><h3>Order from: {{ i.cust.name }}</h3>
                <h3>Phone number: {{ i.cust.mob }}</h3>
                <h3>Pin: {{ i.cust.pin }}</h3>
            <h3>
                {{ i.cust.address }}
            </h3>

                <h4>{{ i.cust.city }}</h4>
                <h4>{{ i.cust.state }}</h4>
                <a href="{% url 'app:soonn' i.id %}" class="btn btn-dark my-2">Delivered</a>
                </center>
        </div>
        <div class="col-md-3">
            {% for j in i.products.all %}
                <img src="{{ j.img.url }}" width="100px" height="100px">
                <h4>{{ j.name }}</h4>
                <h4>{{ j.price }}</h4>
                <h4>{{ j.brand }}</h4>

                {% endfor %}
        </div>

        </div>
        <h2>Total cash : {{ i.cash }}</h2>
        <hr><hr>
    {% endfor %}

</body>
</html>

templates/thanks.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
{% include 'navbar.html' %}


    <div class="row my-4">
    <div class="col-md-4">
        <center><img src="{{ a.img.url }}" width="280px" height="auto"></center>
    </div>
    <div class="col-md-4 my-5">
        <h2 class="text-danger">{{ a.name }}</h2>
        <h3>Brand: {{ a.brand }}</h3>
                <h3 class="text-primary">Thank You Mr.{{ user.customer.name }}. </h3>
                <h5>Your Order has been placed and will be delivered to you within 7 working days.</h5>
                <center><h3>Just pay Rs {{ a.price }}, After receiving your order.</h3></center>
    </div>
    <div class="col-md-3 my-5">
        <h3>Return Policy</h3>
        <center>We are always providing a quality product to our customers. In case the product is damaged or in any other case <u>Easily return policy is available</u> within 7 working days. </u> </center>
    </div>
    </div>

    <hr>
    <center><h2 class="text-primary">You can also try </h2>
        <h3>Our More collection</h3>
    </center>

    <div class="container">
    <div class="row my-4">
        <div class="row bg-white">
            {% for j in c.product_set.all %}
                <center>
                    <div class="item">
                        <a href="{% url 'app:yoo' j.id %}"><img src="{{ j.img.url }}" width="250px" height="250px" class="img m-3"></a><br>
                        <h3 class="m-3 ">{{ j.name }}</h3>
                        <p class="m-2">Rs{{ j.price }} Only/</p>
                    </div>
                </center>
            {% endfor %}
            <br>
            <hr>
    </div>
    </div>
    </div>


{% endblock %}

templates/yoo.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <style>
    .picbig{
        position:absolute;
        width:0px;
        -webkit-transition:width 0.3s linear 0s;
        transition:width 0.3s linear 0s;
        z-index:10;
    }
    .pic:hover + .picbig{
        width:500px;
    }
    </style>
{% endblock %}
{% block body %}
{% include 'navbar.html' %}

<div class="row">

        <div class="col-md-4 m-1">
            <img src="{{ a.img.url }}" class="img-thumbnail pic" width="300px" height="auto" >
            <img src="{{ a.img.url }}" class="img-thumbnail picbig" height="auto" >

        </div>
        <div class="col-md-5">
            <h3>{{ a.name }}</h3>
            <p>{{ a.brand }} </p>
            <hr>
            <h3 class="text-primary">{{ msg }}</h3>

            <h2>Only on Shopkart at Rs <u>{{ a.price }}</u></h2>
            <p>You can choose any of the Payment method to get your order.</p>
            <h3 class="text-danger">CASH ON DELIVERY is available</h3>
            <hr>
            <p>In Stock only {{ a.stock }} left !hurry Up</p>
            <p>Guaranteed delivery to pincode 226016 - Lucknow by Tomorrow 9pm with Same-Day Delivery — Order in the next 12 hours and 16 minutes Details</p>
            <h4>{{ a.features }}</h4>
        </div>
        <div class="col-md-2 p-3">
            <div class="card p-3">
                <h4>100% Quality Assurance</h4>
                <h4>At Shopkart</h4>
                <hr>
                {% if user.customer %}
                    <a href="{% url 'app:nope' a.id %}" class="btn btn-primary">Click Here for Cash On delivery</a>

                    <a href="/sumi" class="btn btn-outline-primary">Add To Cart</a>
                {% else %}
                <a href="{% url 'app:top' a.id %}"><div class="btn btn-outline-danger">Buy Now</div></a>
                {% endif %}
                <hr>
            </div>
        </div>
        </div><hr>
    <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-8">
        <h3 class="text-danger">
            Save Extra with 2 Offers
        </h3>
        <ul>
            <li>Get 10% cashback up to Rs. 100 using Visa Signature or Visa Infinite cards. Shop during the Visa Shopping Days starting 20th to end of every month. Applicable on shopping, recharges and bill payments. Cashback within 3 days from shipment.</li>
            <li>Get 10% cashback using RuPay cards. Max Cashback - INR 100 if you are using RuPay card for first time on Amazon. INR 25 if you have used RuPay card earlier. Check here for your cashback eligibility Here's how</li>
            <li><p>Get 25% back up to Rs.50 using Amazon Pay UPI. For Android App customers only. Valid once during the offer period. Cashback within 10 days. Set up Amazon Pay UPI Here's how</p></li>
        </ul>
    </div>
    </div>
    <hr>
    <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-8">
        <h3 class="text-danger">
            Product description
        </h3>
        <p>When you want to look your very best, Philips has the right grooming solution for you. The new Philips 3000 series trimmers capture more low lying hair for efficient, even trimming results, so you can easily achieve the 3-day stubble, short beard or long beard look you want. With its innovative Lift and Trim system the new trimmers cut up to 30 percent faster. Easy to use and built to last, the new trimmers last up to 6 x longer vs ordinary trimmers.  Self-sharpening blades are long lasting and stay as sharp as on day one, while rounded tips and combs are gentle on your skin preventing irritation.</p>
    </div>
    </div>

{% block javascript %}
    <script src="{% static 'bootstrap/js/ajax.jquery.min.js' %}"></script>
    <script src="{% static 'jquery.magnify.js' %}"></script>
    <script src="{% static 'jquery.magnify-mobile.js' %}"></script>

    {% endblock %}


{% endblock %}

{% include 'footer.html' %}